#! /usr/bin/env python
# -.- coding: utf-8 -.-

# GNOME Activity Journal
#
# Copyright © 2009 Seif Lotfy <seif@lotfy.com>
# Copyright © 2010 Siegfried Gevatter <siegfried@gevatter.com>

import gtk
import gettext

from src.main import Portal

gettext.install('gnome-activity-journal', 'build/mo', unicode=True)

if __name__ == '__main__': 
    portal = Portal(object)
    gtk.main()
